name: masiasl_examen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.7.0
  path: ^1.8.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/login.png
    - assets/OIP.jpg
    - assets/crm.png
    - assets/gestor.jpg
    - assets/Software.jpg
    - assets/formulario.jpg

  uses-material-design: true
